spring.application.name=spring_graphql

# DB2 datasource
spring.datasource.url=jdbc:db2://localhost:50000/graphql
spring.datasource.username=db2admin
spring.datasource.password=root
spring.datasource.driver-class-name=com.ibm.db2.jcc.DB2Driver

# JPA / Hibernate
spring.jpa.database-platform=org.hibernate.dialect.DB2Dialect
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true

# Hikari (optionnel)
spring.datasource.hikari.maximum-pool-size=10
spring.datasource.hikari.connection-test-query=SELECT 1 FROM SYSIBM.SYSDUMMY1
spring.graphql.graphiql.enabled=true
spring.graphql.websocket.path=/graphql
logging.level.org.springframework.graphql=DEBUG
